### ISSUE TITLE
Integrar a função de criar tarefas com a API

### ISSUE THREAD

**Issue by JonasHenriqueDev** [upe-garanhuns/pweb-2023.2-laravel#13]
#### Descrição
Na função 'store' em TarefaController, utilizar de uma requisição POST em '/api/tarefas/criar' para armazenar as tarefas no banco de dados do backend.

#### Capturas de Tela
Exemplo do body da requisição:
![image](https://github.com/upe-garanhuns/pweb-2023.2-laravel/assets/68215037/ebbd25ad-e778-4221-96a1-89607ebc976f)

#### Arquivos
App\Http\Controllers\TarefaController;
App\Services\TarefaService;

#### Tarefas
Inclua as tarefas na ordem em que devem ser cumpridas. Inclua links para as linhas de código específicas onde a tarefa deve ser realizada.
- [ ] Utilizar a função parseData para enviar os dados.
- [ ] Atualizar a função store em TarefaController para salvar os dados.

**Comment by mota-pedro** [comment]
Issue duplicada
Problema já foi solucionado
