### ISSUE TITLE
Crie um método em TarefaController para atualizar uma tarefa pelo seu id

### ISSUE THREAD

**Issue by JonasHenriqueDev** [upe-garanhuns/pweb-2023.2-laravel#15]
#### Descrição
Crie um método em TarefaController para atualizar uma tarefa pelo seu id.
Você deve utilizar o endpoint da API -> PUT  api/tarefas/atualizar/{id}

#### Tarefas
Inclua as tarefas na ordem em que devem ser cumpridas. Inclua links para as linhas de código específicas onde a tarefa deve ser realizada.
- [x] Em TarefaService, crie um método AtualizarTarefasPorId.
- [x] Em TarefaController, integre o método updateData com o método show.
- [x] Faça as tarefas listadas em index serem clicáveis para abrir uma nova tela mostrando mais detalhes da tarefa.

**Comment by mateuzinnn** [comment]
irei fazer esta issue.
