### ISSUE TITLE
Criar uma lista para as tarefas

### ISSUE THREAD

**Issue by mateuzinnn** [upe-garanhuns/pweb-2023.2-laravel#4]
Descrição
Criar uma lista para colocar as tarefas cadastradas no site

Capturas de Tela
Exemplo de lista:
![image](https://github.com/upe-garanhuns/pweb-2023.2-laravel/assets/92633258/95761d47-8303-423a-b5ed-eb258b6849d1)

Tarefas
- [ ] Criar a lista

**Comment by mota-pedro** [comment]
irei implementar essa feature

**Comment by mota-pedro** [comment]
Aguardando conexão da API para completar implementação
