### ISSUE TITLE
Criar função para listar/filtrar tarefas concluídas

### ISSUE THREAD

**Issue by mateuzinnn** [upe-garanhuns/pweb-2023.2-laravel#5]
Descrição
Criar uma função no site para listar as tarefas concluídas e não concluídas, filtrar as tarefas concluídas e filtrar as não concluídas também.

Tarefas
- [x] Criar função listar
- [ ] Criar função filtrar concluídas
- [ ] Criar função filtrar não concluídas

**Comment by JonasHenriqueDev** [comment]
irei realizar.

**Comment by JonasHenriqueDev** [comment]
Parte da issue está duplicada, já existe uma issue para listar as tarefas. #4. Por favor @mateuzinnn ou @mota-pedro confirmem para mim.
