### ISSUE TITLE
Conectar com API

### ISSUE THREAD

**Issue by mota-pedro** [upe-garanhuns/pweb-2023.2-laravel#6]
#### Descrição
Realizar a conexão do projeto com a API Gestão de Tarefas (https://github.com/JonasHenriqueDev/api-gestao-tarefas).

#### Tarefas
- [x] #11
- [x] Criar classe TarefaService para encapsular a lógica de interação com a API
- [x] Registar TarefaService em App/Providers/AppServiceProvider
- [x] Criar função fetchData() em TarefaController para buscar dados na API

**Comment by JonasHenriqueDev** [comment]
vou realizar essa issue.
